### ISSUE TITLE
设备显示不全

### ISSUE THREAD

**Issue by xgdgsc** [iKineticate/BlueGauge#1]
![image](https://github.com/user-attachments/assets/40257e4d-e0ff-439a-bde2-bcccf36f454f)
![image](https://github.com/user-attachments/assets/c2fd78ff-fb13-49fe-9732-b65ef644e75d)

**Comment by iKineticate** [comment]
试试新版[BlueGauge v0.1.1](https://github.com/iKineticate/BlueGauge/releases/tag/0.1.1)看看能否行得通，不行麻烦你用这个找找看有没有你的(低功耗)蓝牙设备
[find_bluetooth_le.zip](https://github.com/user-attachments/files/16799814/find_bluetooth_le.zip)

**Comment by xgdgsc** [comment]
```
PS D:\Downloads\find_bluetooth_le> .\find_bluetooth_le-arm64.exe
设备: HUKE T3
设备: QCAUD Wave Speaker Headset
设备: QCAUD Topology Bluetooth HFP Speaker
设备: GOC - 上
设备: GOC
设备: QCAUD Wave Microphone Headset
设备: Bluetooth Keyboard
设备: Bluetooth LE Device 4d868c1cdb02
设备: HUAWEI FreeBuds Pro 2
设备: RICOH M C2000 (5c1bef)
设备: USB Type-C Digital AV Adapter
设备: WH-1000XM3
设备: QCAUD Wave Microphone
设备: QCAUD Wave Bluetooth HFP Speaker
设备: QCAUD Wave Speaker
设备: RK-H87RGB5.0
设备: QC Back Camera
设备: QCAUD Wave Microphone Array
设备: QCAUD Topology A2DP
设备: Rapoo Gaming Mouse
设备: 耳机 (2- HUAWEI FreeBuds Pro 2)
设备: GSC30
设备: Qualcomm(R) Aqstic(TM)
设备: Internal Microphone Array (Qualcomm(R) Aqstic(TM) Audio Adapter Device)
设备: HUAWEI FreeLace
设备: QCAUD Topology Bluetooth HFP Microphone
设备: QCAUD Wave USBC Headset Microphone
设备: USB 2.0 Hub
设备: QC Front Camera
设备: EDIFIER S301
设备: GOC - 后
设备: QCAUD Topology USBC Speaker Headset
设备: Generic Monitor (PHL 243i7Q)
设备: QCAUD Wave Bluetooth HFP Microphone
设备: Microsoft Trusted Audio Drivers
设备: QCAUD Wave A2DP
设备: QC Auxiliary Camera
设备: WH-1000XM3 Hands-Free
设备: QCAUD Wave Display Audio
设备: QCAUD Wave USBC Speaker Headset
设备: HUAWEI FreeLace Hands-Free
设备: Tee/Sink-to-Sink 转换程序
设备: Generic Monitor (2490W1)
设备: USB2.0 Hub
设备: Microsoft GS 波表合成器
设备: 耳机 (HUAWEI FreeBuds Pro 2 Hands-Free)
设备: Microsoft Print to PDF
设备: QCAUD Topology USBC Headset Microphone
设备: HUAWEI FreeBuds Pro 2 Hands-Free
设备: 2490W1 (Qualcomm(R) Aqstic(TM) Audio Adapter Device)
设备: 耳机 (2- WH-1000XM3)
设备: iQOO 12 Hands-Free HF Audio
设备: 扬声器 (Qualcomm(R) Aqstic(TM) Audio Adapter Device)
设备: GSC30 Hands-Free HF Audio
设备: 耳机 (WH-1000XM3 Hands-Free)
设备: PDF-XChange Lite


低功耗蓝牙设备: RK-H87RGB5.0
低功耗蓝牙设备: HUKE T3
低功耗蓝牙设备:
```
![image](https://github.com/user-attachments/assets/080761b6-6575-406a-803b-551ebb890134)
还有一个不行

**Comment by xgdgsc** [comment]
我试了 https://learn.microsoft.com/en-us/answers/questions/1156194/bluetooth-device-battery-indicator-display-in-syst 这个脚本可以获取正确的数

**Comment by iKineticate** [comment]
那个脚本好像是用WMI查询的，麻烦你在试一下[find_bluetooth_le.zip](https://github.com/user-attachments/files/16823869/find_bluetooth_le.zip)，看看没有显示电量的设备的GattChar Value是符合当前电量的。如果仍扫描不到设备或者电量，我试试看看WMI

**Comment by iKineticate** [comment]
> 我试了 https://learn.microsoft.com/en-us/answers/questions/1156194/bluetooth-device-battery-indicator-display-in-syst 这个脚本可以获取正确的数

似乎发现问题所在了，一些蓝牙设备不是低功耗蓝牙
`Get-PnpDevice -Class 'System' -InstanceId 'BTHENUM\*'`
`Get-PnpDevice -Class 'Bluetooth' -InstanceId 'BTHLE\*'`
![image](https://github.com/user-attachments/assets/6629b4d6-d251-4250-88f2-52afd77821b6)
后续更新软件测试
